version: "3.8"

services:
  deepseek-cli:
    build:
      context: .
      dockerfile: dockerfile 
    container_name: deepseek-cli
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./data:/code/data
      - ./model:/code/model
      - ./mutap:/code/mutap
      - ./scripts:/code/scripts
      - ./output:/code/output
      - ./main.py:/code/main.py
      - ./test_pynguin:/code/test_pynguin
      - ./tmp:/code/tmp
    working_dir: /code
    command: ["/venv/bin/python", "main.py"]
    stdin_open: true         # Required for interactive terminal input
    tty: true