version: "3.9"

services:
  deepseek-cli:
    build:
      context: .
      dockerfile: dockerfile
    image: deepseek-coder 
    container_name: deepseek-cli
    volumes:
      - ./data:/code/data
      - ./model:/code/model
      - ./mutap:/code/mutap
      - ./scripts:/code/scripts
      - ./output:/code/output
      - ./main.py:/code/main.py
      - ./tmp:/code/tmp
    working_dir: /code
    stdin_open: true         # Required for interactive terminal input
    tty: true